Service:
  type: object
  properties:
    alive:
      type: integer
      description: Wether the service is alive or not.
    managed:
      type: integer
      description: Wether the service is managed or not.
    enabled:
      type: integer
      description: Wether the service is enabled or not.
    pid:
      type: integer
      description: The service PID.

ServiceStart:
  type: object
  properties:
    pid:
      type: integer
      description: The service PID.
    start:
      type: integer
      description: Wether the service was started or not.

ServiceStop:
  type: object
  properties:
    pid:
      type: integer
      description: The service PID.
    start:
      type: integer
      description: Wether the service was stopped or not.

ServiceRestart:
  type: object
  properties:
    pid:
      type: integer
      description: The service PID.
    restart:
      type: integer
      description: Wether the service was restarted or not.

ServiceEnable:
  type: object
  properties:
    pid:
      type: integer
      description: The service PID.
    start:
      type: integer
      description: Wether the service was enabled or not.

ServiceDisable:
  type: object
  properties:
    pid:
      type: integer
      description: The service PID.
    start:
      type: integer
      description: Wether the service was disabled or not.
